/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
export async function seed(knex) {
  await knex("strategies").del();
  await knex("strategies").insert([
    {
      id: 1,
      name: "",
      type: "",
      description: "",
      emotional_state: "",
      avg_rating: 0,
    },
    {
      id: 2,
      name: "",
      type: "",
      description: "",
      emotional_state: "",
      avg_rating: 0,
    },
    {
      id: 3,
      name: "",
      type: "",
      description: "",
      emotional_state: "",
      avg_rating: 0,
    },
    {
      id: 4,
      name: "",
      type: "",
      description: "",
      emotional_state: "",
      avg_rating: 0,
    },
    {
      id: 5,
      name: "",
      type: "",
      description: "",
      emotional_state: "",
      avg_rating: 0,
    },
    {
      id: 6,
      name: "",
      type: "",
      description: "",
      emotional_state: "",
      avg_rating: 0,
    },
    {
      id: 7,
      name: "",
      type: "",
      description: "",
      emotional_state: "",
      avg_rating: 0,
    },
    {
      id: 8,
      name: "",
      type: "",
      description: "",
      emotional_state: "",
      avg_rating: 0,
    },
    {
      id: 9,
      name: "",
      type: "",
      description: "",
      emotional_state: "",
      avg_rating: 0,
    },
    {
      id: 10,
      name: "",
      type: "",
      description: "",
      emotional_state: "",
      avg_rating: 0,
    },
    {
      id: 11,
      name: "",
      type: "",
      description: "",
      emotional_state: "",
      avg_rating: 0,
    },
    {
      id: 12,
      name: "",
      type: "",
      description: "",
      emotional_state: "",
      avg_rating: 0,
    },
    {
      id: 13,
      name: "",
      type: "",
      description: "",
      emotional_state: "",
      avg_rating: 0,
    },
    {
      id: 14,
      name: "",
      type: "",
      description: "",
      emotional_state: "",
      avg_rating: 0,
    },
    {
      id: 15,
      name: "",
      type: "",
      description: "",
      emotional_state: "",
      avg_rating: 0,
    },
  ]);
}
